### ISSUE TITLE
How to input multi tensor to NNOnnx?

### ISSUE THREAD

**Issue by Songxinlei** [torinos-yt/NNOnnx#1]
Hi，now, I have  three tensors. I need input them to NNOnnx，what should I do? 
I would appreciate it if you reply me .Thank you!

**Comment by torinos-yt** [comment]
If you already have three tensors that are inputs to a pre-trained model, you can for example bind tensors to the three inputs as follows.
```
var session = NNSession.CreateSessionWithCuda(modelPath);

// declare tensors as GraphicsBuffer
var inputBuffer0 = session.InputNodes[0].CreateTensorBuffer();
var inputBuffer1 = session.InputNodes[1].CreateTensorBuffer();
var inputBuffer2 = session.InputNodes[2].CreateTensorBuffer();

// convert texture data to tensor
TensorUtil.TextureToTensorBuffer(session.InputNodes[0], texture0, inputBuffer0);
TensorUtil.TextureToTensorBuffer(session.InputNodes[1], texture1, inputBuffer1);
TensorUtil.TextureToTensorBuffer(session.InputNodes[2], texture2, inputBuffer2);

// bind  tensors
session.BindInput(session.InputNodes[0], inputBuffer0);
session.BindInput(session.InputNodes[1], inputBuffer1);
session.BindInput(session.InputNodes[2], inputBuffer2);

session.Inference();
```
Although NNOnnx currently supports NCHW format texture input through `TensorUtil.TextureToTensorBuffer()`, but you can be flexible for all input formats by transferring data directly to Cuda using your own compute shader or [MemoryAllocation](https://github.com/torinos-yt/NNOnnx/blob/main/Packages/jp.torinos.nnonnx/Runtime/MemoryAllocation.cs).

See [Background Matting](https://github.com/torinos-yt/NNOnnx/blob/main/Assets/Background%20Matting/BackgroundMattingTest.cs) and [Image Classification](https://github.com/torinos-yt/NNOnnx/blob/main/Assets/Image%20Classificartion/ResNetTest.cs) in the project for related examples.

**Comment by Songxinlei** [comment]
Thank you very much for your reply! Yes, I have implemented multi-input this way before.
