### ISSUE TITLE
Dynamic ONNX Model cant work?

### ISSUE THREAD

**Issue by Songxinlei** [torinos-yt/NNOnnx#3]
Dynamic onnx model .DynamicShape cant work.Is there any way to accept dynamic onnx models

**Comment by torinos-yt** [comment]
Several APIs provide an overload that accepts an array of integers specifying the tensor's shape to support dynamic shape. For example [this](https://github.com/torinos-yt/NNOnnx/blob/822c2124e73d66df08c02a7b5ca266f745f85fbe/Packages/jp.torinos.nnonnx/Runtime/NNSession.cs#L147-L155).

There is also a [sample](https://github.com/torinos-yt/NNOnnx/blob/main/Assets/Image%20Classificartion/ResNetTest.cs) that uses this to use an onnx model with a dynamic shape.

**Comment by torinos-yt** [comment]
Close the issue once, but feel free to reopen it if not resolved.
